title: the memoryleak zone
description: memoryleak's personal corner of the internet
url: ""
baseurl: ""
markdown: kramdown

collections:
  posts:
    permalink: /pages/blog/:slug.html

exclude:
  - Gemfile
  - Gemfile.lock
